apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dispatch-event-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dispatch-event-manager-cluster-role
subjects:
- kind: ServiceAccount
  name: dispatch-event-manager-service-account
  namespace: dispatch
